---
title: "Exercise week 4"
author: "Aloïs THOMAS"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(rtracklayer)
  library(epiwraps)
  library(GenomicRanges)
})
ah <- AnnotationHub()
```


#Downloading the data

```{r, eval=FALSE}
#p300
download.file("https://www.encodeproject.org/files/ENCFF653YVR/@@download/ENCFF653YVR.bed.gz", "p300.bed.gz", mode = "wb")

#H3K4me1
download.file("https://www.encodeproject.org/files/ENCFF426IIV/@@download/ENCFF426IIV.bed.gz", "H3K4me1.bed.gz", mode = "wb")

#H3K27ac
download.file("https://www.encodeproject.org/files/ENCFF212HAG/@@download/ENCFF212HAG.bed.gz", "H3K27ac.bed.gz", mode = "wb")

#H3K4me3
download.file("https://www.encodeproject.org/files/ENCFF331RHM/@@download/ENCFF331RHM.bed.gz", "H3K4me3.bed.gz", mode = "wb")

#H3K27me3
download.file("https://www.encodeproject.org/files/ENCFF105NKG/@@download/ENCFF105NKG.bed.gz", "H3K27me3.bed.gz", mode = "wb")
```
# Import files
```{r}
H3K4me3_peaks <- rtracklayer::import("H3K4me3.bed.gz", format="narrowPeak")
H3K4me1_peaks <- rtracklayer::import("H3K4me1.bed.gz", format="narrowPeak")
H3K27ac_peaks <- rtracklayer::import("H3K27ac.bed.gz", format="narrowPeak")
H3K27me3_peaks <- rtracklayer::import("H3K27me3.bed.gz", format="narrowPeak")
p300_peaks <- rtracklayer::import("p300.bed.gz", format="narrowPeak")
```

# Overlap calculation

```{r}
marks <- list(H3K4me3_peaks, H3K4me1_peaks, H3K27ac_peaks, H3K27me3_peaks)
overlaps <- lapply(marks, function(x) findOverlaps(p300_peaks, x))
proportions <- sapply(overlaps, length) / length(p300_peaks)
proportions <- round(proportions, 4)

names(proportions) <- c("H3K4me3", "H3K4me1", "H3K27ac", "H3K27me3")
print(paste(names(proportions), proportions*100, "%"))

```


